// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	beginRun: () => __TAURI_INVOKE<number>("begin_run"),
	cancelCurrentRun: () => __TAURI_INVOKE<null>("cancel_current_run"),
	initFfmpeg: () => __TAURI_INVOKE<string>("init_ffmpeg"),
	prepareAudioForAi: (runId: number, inputPath: string) => __TAURI_INVOKE<AudioInfo>("prepare_audio_for_ai", { runId, inputPath }),
	/**
	 *  Transcode `source_path` into a seekable `<stem>_preview.m4a` sitting next to
	 *  it, purely for in-app playback preview.
	 * 
	 *  The analysis audio is Opus in an Ogg container, and the source media's own
	 *  audio track is often a codec the webview can't decode. WKWebView (macOS) can
	 *  neither seek Ogg/Opus (it reports a bogus duration and mis-seeks) nor decode
	 *  many source codecs, so segment previews need a transcoded, seekable file.
	 *  AAC in an MP4/M4A container with `+faststart` (moov atom at the front) plays
	 *  and seeks reliably. This does not touch the Ogg/Opus analysis+upload pipeline.
	 * 
	 *  `source_path` is expected to be the already-extracted analysis `.ogg` (fast,
	 *  and on the same original timeline), but any decodable audio/video file works.
	 *  A cached preview is reused when it is at least as new as the source.
	 */
	preparePreviewAudio: (runId: number, sourcePath: string) => __TAURI_INVOKE<string>("prepare_preview_audio", { runId, sourcePath }),
	/**
	 *  The seekable preview audio a previous analysis of `input_path` produced,
	 *  if it is still cached.
	 */
	cachedPreviewAudio: (inputPath: string) => __TAURI_INVOKE<string | null>("cached_preview_audio", { inputPath }),
	/**  Pick short-form clip candidates from the transcript (shorts phase S1). */
	selectClips: (runId: number, llm: LlmConfig, transcript: TranscriptSegment_Deserialize[], request: ClipRequest) => __TAURI_INVOKE<ClipCandidate[]>("select_clips", { runId, llm, transcript, request }),
	/**
	 *  Models available at `base_url`. Uses `api_key` when given (a key typed in
	 *  Settings but not saved yet), otherwise the stored key.
	 */
	listModels: (baseUrl: string, apiKey: string | null) => __TAURI_INVOKE<ModelList>("list_models", { baseUrl, apiKey }),
	setApiKey: (key: string) => __TAURI_INVOKE<null>("set_api_key", { key }),
	clearApiKey: () => __TAURI_INVOKE<null>("clear_api_key"),
	hasApiKey: () => __TAURI_INVOKE<boolean>("has_api_key"),
	uploadFile: (runId: number, baseUrl: string, path: string) => __TAURI_INVOKE<string | null>("upload_file", { runId, baseUrl, path }),
	splitAudioForAnalysis: (runId: number, path: string, maxChunkSeconds: number | null, parakeetModelPath: string) => __TAURI_INVOKE<AudioChunk[]>("split_audio_for_analysis", { runId, path, maxChunkSeconds, parakeetModelPath }),
	analyzeAudio: (runId: number, llm: LlmConfig, enforceJsonSchema: boolean, context: string, glossary: string, speakerCount: number | null, removeFillerWords: boolean, audioUri: string | null, audioBase64: string | null) => __TAURI_INVOKE<string>("analyze_audio", { runId, llm, enforceJsonSchema, context, glossary, speakerCount, removeFillerWords, audioUri, audioBase64 }),
	cleanupLocalTranscript: (runId: number, baseUrl: string, model: string, transcript: TranscriptSegment_Deserialize[], context: string, glossary: string, removeFillerWords: boolean) => __TAURI_INVOKE<TranscriptSegment_Serialize[]>("cleanup_local_transcript", { runId, baseUrl, model, transcript, context, glossary, removeFillerWords }),
	mergeTranscriptHypotheses: (runId: number, primaryTranscript: TranscriptSegment_Deserialize[], referenceTranscript: TranscriptSegment_Deserialize[]) => __TAURI_INVOKE<TranscriptSegment_Serialize[]>("merge_transcript_hypotheses", { runId, primaryTranscript, referenceTranscript }),
	transcribeWithParakeet: (runId: number, audioPath: string, parakeetModelPath: string, sortformerModelPath: string) => __TAURI_INVOKE<TranscriptSegment_Serialize[]>("transcribe_with_parakeet", { runId, audioPath, parakeetModelPath, sortformerModelPath }),
	/**  Transcribe with CrisperWhisper 2.0 and return editor-ready segments. */
	transcribeWithCrisper: (runId: number, audioPath: string, options: CrisperOptions) => __TAURI_INVOKE<TranscriptSegment_Serialize[]>("transcribe_with_crisper", { runId, audioPath, options }),
	/**  Report whether CrisperWhisper can run, and on what. */
	crisperEnvironmentStatus: (pythonPath: string) => __TAURI_INVOKE<CrisperEnvironmentStatus>("crisper_environment_status", { pythonPath }),
	/**  Create the managed virtual environment and install `crisperwhisper` into it. */
	installCrisperEnvironment: (pythonPath: string, extra: string) => __TAURI_INVOKE<CrisperEnvironmentStatus>("install_crisper_environment", { pythonPath, extra }),
	cutVideo: (runId: number, inputPath: string, segments: Segment[], outputPath: string, quality: ExportQuality) => __TAURI_INVOKE<null>("cut_video", { runId, inputPath, segments, outputPath, quality }),
	exportClips: (runId: number, inputPath: string, segments: ClipSegment[], outputDir: string, fastMode: boolean, quality: ExportQuality) => __TAURI_INVOKE<null>("export_clips", { runId, inputPath, segments, outputDir, fastMode, quality }),
	readFileAsBase64: (path: string) => __TAURI_INVOKE<string>("read_file_as_base64", { path }),
	openFolder: (path: string) => __TAURI_INVOKE<null>("open_folder", { path }),
	writeTextFile: (path: string, content: string) => __TAURI_INVOKE<null>("write_text_file", { path, content }),
	readTextFile: (path: string) => __TAURI_INVOKE<string>("read_text_file", { path }),
	pathExists: (path: string) => __TAURI_INVOKE<boolean>("path_exists", { path }),
	/**
	 *  Grant the webview's asset protocol access to a user-selected media file and
	 *  its directory at runtime. The static `assetProtocol.scope` in tauri.conf.json
	 *  only covers `$HOME`/`$TEMP`; this extends access to files anywhere the user
	 *  picks them (e.g. external volumes) so `convertFileSrc` can load the source
	 *  media and the extracted `.ogg` sidecar written alongside it.
	 */
	allowMediaAccess: (path: string) => __TAURI_INVOKE<null>("allow_media_access", { path }),
	detectSilence: (runId: number | null, path: string, minDuration: number | null) => __TAURI_INVOKE<SilenceInterval[]>("detect_silence", { runId, path, minDuration }),
	removeSilence: (runId: number | null, path: string, minDuration: number | null) => __TAURI_INVOKE<ProcessedAudio>("remove_silence", { runId, path, minDuration }),
	translateTranscript: (runId: number, baseUrl: string, model: string, transcript: TranscriptSegment_Deserialize[], targetLanguage: string, context: string) => __TAURI_INVOKE<string>("translate_transcript", { runId, baseUrl, model, transcript, targetLanguage, context }),
	zipLogs: (targetPath: string) => __TAURI_INVOKE<null>("zip_logs", { targetPath }),
	generatePodcast: (runId: number, baseUrl: string, model: string, transcript: string, minDuration: number, maxDuration: number, context: string | null) => __TAURI_INVOKE<string>("generate_podcast", { runId, baseUrl, model, transcript, minDuration, maxDuration, context }),
	refinePodcast: (runId: number, baseUrl: string, model: string, originalTranscript: string, currentScript: string, currentDuration: number | null, targetMin: number, targetMax: number) => __TAURI_INVOKE<string>("refine_podcast", { runId, baseUrl, model, originalTranscript, currentScript, currentDuration, targetMin, targetMax }),
	exportPodcast: (runId: number, inputPath: string, segments: PodcastSegment_Deserialize[], introPath: string | null, outroPath: string | null, startPadding: number | null, endPadding: number | null, outputPath: string) => __TAURI_INVOKE<null>("export_podcast", { runId, inputPath, segments, introPath, outroPath, startPadding, endPadding, outputPath }),
	exportPodcastClips: (runId: number, inputPath: string, segments: PodcastSegment_Deserialize[], startPadding: number | null, endPadding: number | null, outputDir: string) => __TAURI_INVOKE<null>("export_podcast_clips", { runId, inputPath, segments, startPadding, endPadding, outputDir }),
	calculateSegmentsDuration: (segments: PodcastSegment_Deserialize[]) => __TAURI_INVOKE<number | null>("calculate_segments_duration", { segments }),
};

/* Types */
/**  A command failure as the frontend receives it: `{ kind, message }`. */
export type AppError = {
	kind: ErrorKind,
	message: string,
};

/**
 *  One analysis chunk: a file on disk plus its start time (seconds) relative to
 *  the input audio, used to shift transcript timestamps back onto the original
 *  timeline.
 */
export type AudioChunk = {
	path: string,
	start_offset: number,
};

export type AudioInfo = {
	path: string,
	size: number,
	duration: number,
};

export type ClipCandidate = {
	title: string,
	hookLine: string,
	reason: string,
	/**  In playback order. */
	ranges: ClipRange[],
	ratings: ClipRatings,
	signals: ClipSignals,
	/**  Overall rank score, 0-100. */
	score: number,
	duration: number,
	looped: boolean,
};

export type ClipRange = {
	start: number,
	end: number,
	role: ClipRole,
	/**  Index of the first and last transcript segment in the range. */
	firstSegment: number,
	lastSegment: number,
};

/**  The LLM's 1-10 ratings. */
export type ClipRatings = {
	hook: number,
	standalone: number,
	emotion: number,
	info: number,
	/**  How well the closing leads back into the opener (looped clips only). */
	loopContinuity: number,
};

export type ClipRequest = {
	count: number,
	minSeconds: number | null,
	maxSeconds: number | null,
	topic: string | null,
	/**  Allow clips made of several non-contiguous ranges (e.g. a cold open). */
	allowSplicing: boolean,
	/**
	 *  Looped shorts: the opener is the story's resolution and the closing
	 *  line leads back into it.
	 */
	looped: boolean,
};

export type ClipRole = "hook" | "body" | "payoff" | "loop_opener" | "closing";

export type ClipSegment = {
	segments: Segment[],
	label: string | null,
	reason: string | null,
};

/**  Cheap signals measured from the transcript itself. */
export type ClipSignals = {
	speakerChanges: number,
	laughs: number,
	wordsPerSecond: number,
};

export type CrisperEnvironmentStatus = {
	/**  Interpreter that was probed, if one could be found at all. */
	pythonPath: string,
	python: string,
	pythonSupported: boolean,
	minimumPython: string,
	/**  Whether the `crisperwhisper` package imports successfully. */
	installed: boolean,
	crisperwhisperVersion: string | null,
	/**  Installed inference backends: `transformers` and/or `ct2`. */
	backends: string[],
	torchVersion: string | null,
	cuda: boolean,
	mps: boolean,
	/**  Path of the app-managed virtual environment (whether or not it exists). */
	environmentDir: string,
	managedEnvironmentExists: boolean,
	/**  True when a transcription can actually be started. */
	ready: boolean,
	/**  Human-readable reason when `ready` is false. */
	message: string | null,
};

export type CrisperOptions = {
	/**
	 *  Explicit interpreter to use. Empty means: managed environment, then a
	 *  system Python.
	 */
	pythonPath?: string,
	/**
	 *  Size shorthand (`large`/`turbo`/`medium`/`small`), a HuggingFace id, or
	 *  a local model directory.
	 */
	model?: string,
	language?: string,
	/**  `verbatim` (what was said) or `intended` (cleaned up). */
	mode?: string,
	/**  `auto` | `ct2` | `transformers` */
	backend?: string,
	/**  `auto` | `cpu` | `cuda` */
	device?: string,
	/**  `auto` | `float32` | `float16` | `int8_float16` */
	computeType?: string,
	wordTimestamps?: boolean,
	/**  Drop `[UM]`/`[UH]` and split the segment there so the cut excises them. */
	removeFillers?: boolean,
	/**  Same treatment for `[laughter]`, `[breath]`, `[cough]`, ... */
	removeVocalEvents?: boolean,
	/**  Assign speakers with Sortformer (CrisperWhisper does not diarize). */
	diarize?: boolean,
	sortformerModelPath?: string,
	/**  Honoured by Pro models only; standard weights warn and ignore it. */
	hotwords?: string[],
};

/**
 *  What kind of failure an [`AppError`] is, so the frontend can react to it
 *  (e.g. stay quiet on cancellation) without matching message text.
 */
export type ErrorKind = 
/**  The user cancelled the run (or a newer run superseded it). */
"cancelled" | 
/**  Anything else; `message` says what went wrong. */
"failed";

/**  Speed/quality trade-off for an export. */
export type ExportQuality = 
/**  Visually lossless; for final masters. */
"high" | 
/**  Good quality at a sensible size; the default for clips and cuts. */
"balanced" | 
/**  Fast and small; previews and drafts. */
"draft";

/**
 *  The remote LLM a request goes to, as configured in Settings. The API key
 *  is not part of it: the backend reads it from the credential store.
 */
export type LlmConfig = {
	baseUrl: string,
	model: string,
};

/**  Models an endpoint offers, for the model picker in Settings. */
export type ModelList = {
	/**  False when the endpoint has no model-listing route (404). */
	supported: boolean,
	models: string[],
};

export type PodcastSegment = PodcastSegment_Serialize | PodcastSegment_Deserialize;

export type PodcastSegmentType = "content" | "voiceover";

export type PodcastSegment_Deserialize = {
	start: string,
	end: string,
	text: string,
	speaker: string,
	segment_type?: PodcastSegmentType,
	include_reason?: string | null,
	transition_note?: string | null,
};

export type PodcastSegment_Serialize = {
	start: string,
	end: string,
	text: string,
	speaker: string,
	segment_type: PodcastSegmentType,
	include_reason?: string | null,
	transition_note?: string | null,
};

export type ProcessedAudio = {
	path: string,
	silence_intervals: SilenceInterval[],
	offsets: SegmentOffset[],
};

export type Segment = {
	start: string,
	end: string,
};

export type SegmentOffset = {
	min_time: number,
	offset: number,
};

export type SilenceInterval = {
	start: number,
	end: number,
	duration: number,
};

export type TranscriptAlternative = TranscriptAlternative_Serialize | TranscriptAlternative_Deserialize;

export type TranscriptAlternativeSource = TranscriptAlternativeSource_Serialize | TranscriptAlternativeSource_Deserialize;

export type TranscriptAlternativeSource_Deserialize = 
/**
 *  Whichever local engine produced the timed words (Parakeet or
 *  CrisperWhisper). Serialised as `local`; `parakeet` is accepted as an
 *  alias so transcripts saved before the engines were split still load.
 */
"local" | 
/**
 *  Whichever local engine produced the timed words (Parakeet or
 *  CrisperWhisper). Serialised as `local`; `parakeet` is accepted as an
 *  alias so transcripts saved before the engines were split still load.
 */
"parakeet" | "google";

export type TranscriptAlternativeSource_Serialize = 
/**
 *  Whichever local engine produced the timed words (Parakeet or
 *  CrisperWhisper). Serialised as `local`; `parakeet` is accepted as an
 *  alias so transcripts saved before the engines were split still load.
 */
"local" | "google";

export type TranscriptAlternative_Deserialize = {
	source: TranscriptAlternativeSource_Deserialize,
	text: string,
	speaker?: string | null,
	similarityScore?: number | null,
};

export type TranscriptAlternative_Serialize = {
	source: TranscriptAlternativeSource_Serialize,
	text: string,
	speaker?: string | null,
	similarityScore?: number | null,
};

export type TranscriptMergeStatus = TranscriptMergeStatus_Serialize | TranscriptMergeStatus_Deserialize;

export type TranscriptMergeStatus_Deserialize = "matched" | "conflict" | "missing_google" | 
/**
 *  Missing from the local engine's hypothesis. `missing_parakeet` is
 *  accepted as an alias for transcripts saved before the split.
 */
"missing_local" | 
/**
 *  Missing from the local engine's hypothesis. `missing_parakeet` is
 *  accepted as an alias for transcripts saved before the split.
 */
"missing_parakeet";

export type TranscriptMergeStatus_Serialize = "matched" | "conflict" | "missing_google" | 
/**
 *  Missing from the local engine's hypothesis. `missing_parakeet` is
 *  accepted as an alias for transcripts saved before the split.
 */
"missing_local";

export type TranscriptSegment = TranscriptSegment_Serialize | TranscriptSegment_Deserialize;

export type TranscriptSegment_Deserialize = {
	start: string,
	end: string,
	speaker: string,
	text: string,
	words?: TranscriptWord_Deserialize[] | null,
	alternatives?: TranscriptAlternative_Deserialize[] | null,
	mergeStatus?: TranscriptMergeStatus_Deserialize | null,
	activeSource?: TranscriptAlternativeSource_Deserialize | null,
	similarityScore?: number | null,
};

export type TranscriptSegment_Serialize = {
	start: string,
	end: string,
	speaker: string,
	text: string,
	words?: TranscriptWord_Serialize[] | null,
	alternatives?: TranscriptAlternative_Serialize[] | null,
	mergeStatus?: TranscriptMergeStatus_Serialize | null,
	activeSource?: TranscriptAlternativeSource_Serialize | null,
	similarityScore?: number | null,
};

export type TranscriptWord = TranscriptWord_Serialize | TranscriptWord_Deserialize;

export type TranscriptWord_Deserialize = {
	start: string,
	end: string,
	text: string,
	speaker?: string | null,
};

export type TranscriptWord_Serialize = {
	start: string,
	end: string,
	text: string,
	speaker?: string | null,
};

